language: java

jdk:
  - oraclejdk8

install: ./gradlew clean assemble --stacktrace

script:
  - ./gradlew check --stacktrace

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle