language: java

jdk:
  - oraclejdk8

install: ./gradlew clean assemble --stacktrace

script:
  - ./gradlew check --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
   - secure: "D0CAeAEbXVBMCGgY9Md+6plg5bqlfVdbthkHGDIN+vAOpqVK4C72LFQOjvSfGdpMhcXlu6tJBI6NaL2q4abE5oYjPAqBd7Zmqs/jv4iAQjqvk7cydCZq0XNsAGVtsOR7n5eLRAYbq9u5F9aBTcsEtaerqT+Wotr4s+/5P89KJY9EbDduTd4igJ100Vg1aKQwLaumdPqUb0ezfbRrXY3EvMassC/kZXFwqeaFQ/Y60ALohkNjxGiuDLtavEXWVn+tBwGL2dMWv/DXzlf2+1IVCbneSFIJpR0jfPmZdW9WRiipi85kzP3dzHUsw1kL4SW5l1IOGz2nqueF8SyGvqPZwBsmzmDPAx6Y8SmZcxGcylnk6fa7JuRXefVM5bPYTagZVbeGon676HCOoHz7kn+wWybLNqbrbYwMnxbVp5mI0Lw+wiiqsm6L13lvpo5ONFX87q41yQoqc6RpIogasl073RS2Uhwqwv07o4abEkBNREo16VF3fU86PAeNA3m5xH78N3QhDmrO4UnhgcwbISeAymjBF4COBuwxdM27DqGO+dtvsJJztQXf/igVrxc4GUubFN/laaJX80RcZfvrXJulTPl8x6rxbbr3XGW+exrpfYjQ8LcnRBNHgpMDgCHwv/8PQNykhcwg8w4GuW2eSfClaUy9rvIQzapDpo2lk6eYeXg="
   - secure: "dyVL1zKO5PikmOs/qx2Pc7RRec3nF9TAmU51PhQwGkgXLw6GRyLBNIVfnRgoDWSrwriUNPluEEf0wIoTFG6gzauzyCxgJVSZ0QxBMWfbYgFIbx9th4D+B3H0uDw3omPyfQp+KQeb5EQR1BsAEdfsKieUmYF/mtKCGJDd+bq85ulsBtHJ38ZWpUe5hGci//pNAYhO1ogtU6rwRpQ6APgaqBrEtMqE6h7oxZqjByM5LHuhaJ16tc/psOAnC/8paW+wZzaCqmdxUXGll1VSBEHijXyhzi28BwSLGPmriF9uQbWhd5stKTx4WgqVNhJyDJFxaOUF0WWgk+q49QPvYUtM1EcSTxz93i2E3EeV3eHeiQ0g6bSb1QICq7fZBGlnnMRuUsc31si0lofq2Wza7GgWx+FYlfu60B0haKcNPurlhJrlYUS5M9C3/jGXc35kNpyRYJy5vzFuqB+f9Ccu+b+fKKrSs8AXoCxcMjup9DigT8zz1WavZIyDf6csGtMv8jqscNyss2JXTn1OOnH0UmWiUP+Hn+x9hMX/jxE3Q0/6VPo5lTbrFcsh0tbybZjI+HpvMennxqshbi+tLM5jrQCyiAPbChfB5egWoohWXGAXze2XMN57Ku0lDhV/9VLFNzL7+kwyZ13HRfGv0Ci/3BLWFrBL5QCn4iJNOgNOMef7s1Q="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle